import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata = {
    title: "Snacker",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider
        appearance={{
            variables:{
                colorBackground: '#362c36',
                colorText: '#FFFFFF',
                colorTextSecondary: '#FFFFFF',
                colorTextOnPrimaryBackground: '#FFFFFF',
                colorWarning: '#FFFFFF',
                colorDanger: '#FFFFFF',
                colorNeutral: '#FFFFFF',
                colorPrimary: '#FFFFFF',
                colorSuccess: '#FFFFFF',
                colorShimmer: '#FFFFFF',   
            }
        }}>
            <html lang="en">
                <body className={poppins.className}>{children}</body>
            </html>
        </ClerkProvider>
    );
}
